name: PR / Push

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # linting is configured in tox.ini and will run as
        # part of the 3.10 suite
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: python-integration-test-cache

    steps:
      - uses: actions/checkout@v2
      - name: Python ${{ matrix.python-version }} sample
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
          pip install tox tox-gh-actions
          tox
